# Generated by Django 5.2.6 on 2025-09-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_stripe_payment_intent_orderdetail_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
